Repository zowe/zowe-cli, pull requests merged in 2019-02, with the labels that each got.

#194 Enhance jenkinsfile to support all release branches
  Jenkinsfile
  package.json
Labels: review

#195 Enhance jenkinsfile to support all release branches
  Jenkinsfile
  package.json
Labels: review

#198 Update latest jenkins
  Jenkinsfile
  package.json
Labels: review

#199 Enhance jenkinsfile to support all release branches
  Jenkinsfile
  package.json
Labels: review

#193 Dir to uss
  package-lock.json
  packages/zosfiles/__tests__/__integration__/cli/upload/dtp/__snapshots__/cli.files.upload.dtp.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__scripts__/command/command_upload_dtu.sh
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__scripts__/command_upload_dtu_help.sh
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__snapshots__/cli.files.upload.dtu.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/cli.files.upload.dtu.integration.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/upload/Upload.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/upload/failtestfiles/main.exe
  packages/zosfiles/__tests__/__system__/api/methods/upload/failtestfiles/test1.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/ascii_file.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/bin_file.pax
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_ascii/subdir_ascii_file1.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_ascii/subdir_ascii_file2.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_bin/subdir_bin_file1.pax
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_bin/subdir_bin_file2.pax.Z
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__scripts__/command/command_upload_dtu.sh
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__scripts__/command/command_upload_dtu_fully_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.definition.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/__snapshots__/DirToUSS.definition.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/dtu/__snapshots__/DirToUSS.handler.unit.test.ts.snap
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/methods/create/Create.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadMap.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadOptions.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/upload/Upload.definition.ts
  packages/zosfiles/src/cli/upload/Upload.options.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.definition.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.handler.ts
  packages/zosfiles/src/cli/upload/ftu/FileToUSS.handler.ts
Labels: review

#202 Added Start API plus its unit and system tests
  packages/workflows/__tests__/__system__/Start.system.test.ts
  packages/workflows/__tests__/__system__/testfiles/demo.xml
  packages/workflows/__tests__/api/Start.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/Start.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/doc/IStartWorkflow.ts
Labels: review

#210 Fix CR-LF problem
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/ascii_file.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_ascii/subdir_ascii_file1.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/__data__/command_upload_dtu_dir/command_upload_dtu_subdir_ascii/subdir_ascii_file2.txt
Labels: review

#212 Update package version because of dir-to-uss
  .gitignore
  package-lock.json
  package.json
Labels: review

#211 Workflow list final
  packages/workflows/__tests__/__system__/ListWorkflows.system.test.ts
  packages/workflows/__tests__/api/ListWorkflows.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/ListWorkflows.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/WorkflowValidator.ts
  packages/workflows/src/api/doc/IWorkflows.ts
  packages/workflows/src/api/doc/IWorkflowsInfo.ts
Labels: review

#217 Ensure password is masked in the log
  __tests__/__system__/cli/logging/LoggingCredentials.system.test.ts
  __tests__/__system__/cli/logging/__scripts__/sample_commands_connect_options.sh
Labels: review

#219 Enhancement/142
  Jenkinsfile
  package.json
Labels: review

#227 Version 1.0.2 of zowe-cli-version-controller
  Jenkinsfile
Labels: review

#203 Us559527 create delete workflow cli
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_ds.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_ds_empty.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_uss.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_uss_empty.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/create_workflow_ds_help.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/create_workflow_uss_help.sh
  packages/workflows/__tests__/__system__/cli/create/__snapshots__/cli.workflows.create.common.system.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/cli.workflows.create.common.system.test.ts
  packages/workflows/__tests__/__system__/cli/delete/__scripts__/command/command_delete_workflow_key.sh
  packages/workflows/__tests__/__system__/cli/delete/__scripts__/delete_active_workflow_help.sh
  packages/workflows/__tests__/__system__/cli/delete/__snapshots__/cli.workflows.delete.common.system.test.ts.snap
  packages/workflows/__tests__/__system__/cli/delete/cli.workflows.delete.common.system.test.ts
  packages/workflows/__tests__/__system__/testfiles/demods.xml
  packages/workflows/__tests__/cli/Workflows.definition.unit.test.ts
  packages/workflows/__tests__/cli/__snapshots__/Workflows.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/Create.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/create/Create.definition.unit.test.ts
  packages/workflows/__tests__/cli/create/__snapshots__/Create.common.handler.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/__snapshots__/Create.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/dataset/Dataset.definition.unit.test.ts
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/UssFile.definition.unit.test.ts
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/Delete.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/delete/Delete.definition.unit.test.ts
  packages/workflows/__tests__/cli/delete/__snapshots__/Delete.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/deleteActiveWorkflow/__snapshots__/deleteActiveWorkflow.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/deleteActiveWorkflow/deleteActiveWorkflow.definition.unit.test.ts
  packages/workflows/src/api/Create.ts
  packages/workflows/src/cli/Workflows.definition.ts
  packages/workflows/src/cli/create/Create.common.handler.ts
  packages/workflows/src/cli/create/Create.common.options.ts
  packages/workflows/src/cli/create/Create.definition.ts
  packages/workflows/src/cli/create/dataset/Dataset.definition.ts
  packages/workflows/src/cli/create/ussfile/UssFile.definition.ts
  packages/workflows/src/cli/delete/Delete.common.handler.ts
  packages/workflows/src/cli/delete/Delete.definition.ts
  packages/workflows/src/cli/delete/deleteActiveWorkflow/DeleteActiveWorkflow.definition.ts
  packages/workflows/src/cli/delete/deleteActiveWorkflow/DeleteActiveWorkflow.options.ts
Labels: release-minor, review

#226 Workflow CANCEL API
  packages/workflows/__tests__/__system__/Cancel.system.test.ts
  packages/workflows/__tests__/api/Cancel.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/Cancel.ts
  packages/workflows/src/api/WorkflowConstants.ts
Labels: release-minor, review

#233 fix #222 - remove @types/lodash
  package.json
Labels: release-patch, review

#230 Start CLI
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/command/command_start_workflow_full.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/start_workflow_full_help.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__snapshots__/cli.workflows.start.workflowFull.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/cli.workflows.start.workflowFull.integration.test.ts
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/command/command_start_workflow_step.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/start_workflow_step_help.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__snapshots__/cli.workflows.start.workflowStep.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/cli.workflows.start.workflowStep.integration.test.ts
  packages/workflows/__tests__/__system__/api/Create.system.test.ts
  packages/workflows/__tests__/__system__/api/Delete.system.test.ts
  packages/workflows/__tests__/__system__/api/ListWorkflows.system.test.ts
  packages/workflows/__tests__/__system__/api/Properties.system.test.ts
  packages/workflows/__tests__/__system__/api/Start.system.test.ts
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_full.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_step.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_step_plus_following.sh
  packages/workflows/__tests__/__system__/cli/start/cli.workflows.start.common.system.test.ts
  packages/workflows/__tests__/__system__/testfiles/demo.xml
  packages/workflows/__tests__/cli/start/Start.definition.unit.test.ts
  packages/workflows/__tests__/cli/start/__snapshots__/Start.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/workflowFull/WorkflowFull.definition.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowFull/WorkflowFull.handler.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowFull/__snapshots__/WorkflowFull.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/workflowStep/WorkflowStep.definition.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowStep/WorkflowStep.handler.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowStep/__snapshots__/WorkflowStep.definition.unit.test.ts.snap
  packages/workflows/src/api/Properties.ts
  packages/workflows/src/api/doc/IWorkflowInfo.ts
  packages/workflows/src/cli/Workflows.definition.ts
  packages/workflows/src/cli/start/Start.common.options.ts
  packages/workflows/src/cli/start/Start.definition.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.definition.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.handler.ts
  packages/workflows/src/cli/start/workflowStep/WorkflowStep.definition.ts
  packages/workflows/src/cli/start/workflowStep/WorkflowStep.handler.ts
Labels: release-minor, review

#228 add FAQ, fix links
  README.md
Labels: documentation, release-patch, review

#232 zos-workflows list api enhancement
  packages/workflows/__tests__/api/ListWorkflows.unit.test.ts
  packages/workflows/src/api/ListWorkflows.ts
  packages/workflows/src/api/doc/IActiveWorkflows.ts
Labels: release-minor, review

#236 Enhancement/130
  .npmrc
  Jenkinsfile
  package.json
  packages/main.ts
  packages/workflows/__tests__/__system__/testfiles/demods.xml
Labels: release-major, review

#247 Change performance event names in main.ts
  packages/main.ts
Labels: release-patch, review

#237 Archive api
  packages/workflows/__tests__/__system__/Archive.system.test.ts
  packages/workflows/__tests__/__system__/__snapshots__/Archive.system.test.ts.snap
  packages/workflows/__tests__/api/Archive.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/ArchiveWorkflow.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/doc/IArchivedWorkflow.ts
Labels: release-minor, review

#238 update CLIReadme
  docs/CLIReadme.md
Labels: release-patch, review

#249 Archive active workflow cli
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__scripts__/archive_workflow_help.sh
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__scripts__/command/command_archive_workflow.sh
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__scripts__/command/command_archive_workflow_wfkey.sh
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__scripts__/command/command_archive_workflow_wfname.sh
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__snapshots__/cli.workflows.archive.workflow.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/archive/workflow/cli.workflows.archive.workflow.integration.test.ts
  packages/workflows/__tests__/__system__/cli/archive/workflow/__scripts__/command/command_archive_workflow_key.sh
  packages/workflows/__tests__/__system__/cli/archive/workflow/__scripts__/command/command_archive_workflow_name.sh
  packages/workflows/__tests__/__system__/cli/archive/workflow/cli.workflows.archive.workflow.system.test.ts
  packages/workflows/__tests__/cli/archive/Archive.definition.unit.test.ts
  packages/workflows/__tests__/cli/archive/__snapshots__/Archive.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/archive/workflow/Archive.workflow.definition.unit.test.ts
  packages/workflows/__tests__/cli/archive/workflow/Archive.workflow.handler.unit.test.ts
  packages/workflows/__tests__/cli/archive/workflow/__snapshots__/Archive.workflow.definition.unit.test.ts.snap
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/cli/Workflows.definition.ts
  packages/workflows/src/cli/archive/Archive.definition.ts
  packages/workflows/src/cli/archive/Archive.handler.ts
  packages/workflows/src/cli/archive/Archive.options.ts
  packages/workflows/src/cli/archive/workflow/Archive.workflow.definition.ts
Labels: release-minor, review

#239 Add option to print only the servlet key on zowe zos-tso start as
  package.json
  packages/zostso/__tests__/__integration__/cli/start/__snapshots__/cli.zos-tso.start.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/start/__snapshots__/cli.zos-tso.start.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/stop/__snapshots__/cli.zos-tso.stop.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__system__/cli/start/__scripts__/address-space/address_space_sko.sh
  packages/zostso/__tests__/__system__/cli/start/cli.zos-tso.start.address-space.system.test.ts
  packages/zostso/__tests__/cli/start/address-space/__snapshots__/AddressSpace.definition.unit.test.ts.snap
  packages/zostso/src/cli/start/address-space/AddressSpace.definition.ts
  packages/zostso/src/cli/start/address-space/AddressSpace.handler.ts
Labels: release-minor, review

#240 Servlet key only -- incremental
  packages/zostso/__tests__/__integration__/cli/start/__snapshots__/cli.zos-tso.start.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/start/__snapshots__/cli.zos-tso.start.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/stop/__snapshots__/cli.zos-tso.stop.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__system__/cli/start/__scripts__/address-space/address_space_sko.sh
  packages/zostso/__tests__/__system__/cli/start/cli.zos-tso.start.address-space.system.test.ts
  packages/zostso/__tests__/cli/start/address-space/__snapshots__/AddressSpace.definition.unit.test.ts.snap
  packages/zostso/src/cli/start/address-space/AddressSpace.definition.ts
  packages/zostso/src/cli/start/address-space/AddressSpace.handler.ts
Labels: release-minor, review

#246 223 add uss delete
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__scripts__/command/command_delete_file.sh
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__scripts__/delete_file_help.sh
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__snapshots__/cli.files.delete.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/cli.files.delete.uss.integration.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/delete/DeleteUSSFile.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_directory.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_directory_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_file.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_file_fully_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__snapshots__/cli.files.delete.directory.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__snapshots__/cli.files.delete.file.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/delete/uss/cli.files.delete.directory.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/delete/uss/cli.files.delete.file.system.test.ts
  packages/zosfiles/__tests__/api/methods/delete/Delete.unit.test.ts
  packages/zosfiles/__tests__/cli/delete/uss/Uss.definition.unit.test.ts
  packages/zosfiles/__tests__/cli/delete/uss/Uss.handler.unit.test.ts
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/delete/Delete.definition.ts
  packages/zosfiles/src/cli/delete/uss/Uss.definition.ts
  packages/zosfiles/src/cli/delete/uss/Uss.handler.ts
  packages/zosjobs/__tests__/__system__/cli/submit/local-file/testFileOfLocalJCL.txt
Labels: release-minor, review

#252 223 lts incremental
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__scripts__/command/command_delete_file.sh
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__scripts__/delete_file_help.sh
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__snapshots__/cli.files.delete.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/cli.files.delete.uss.integration.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/delete/DeleteUSSFile.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_directory.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_directory_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_file.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__scripts__/command/command_delete_file_fully_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__snapshots__/cli.files.delete.directory.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/delete/uss/__snapshots__/cli.files.delete.file.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/delete/uss/cli.files.delete.directory.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/delete/uss/cli.files.delete.file.system.test.ts
  packages/zosfiles/__tests__/api/methods/delete/Delete.unit.test.ts
  packages/zosfiles/__tests__/cli/delete/uss/Uss.definition.unit.test.ts
  packages/zosfiles/__tests__/cli/delete/uss/Uss.handler.unit.test.ts
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/delete/Delete.definition.ts
  packages/zosfiles/src/cli/delete/uss/Uss.definition.ts
  packages/zosfiles/src/cli/delete/uss/Uss.handler.ts
  packages/zosjobs/__tests__/__system__/cli/submit/local-file/testFileOfLocalJCL.txt
Labels: review
