Repository zowe/zowe-cli, pull requests merged in 2019-05, with the labels that each got.

#357 Add encodeURIComponent for wf name string (same as #356)
  packages/workflows/__tests__/api/ListArchivedWorkflows.unit.test.ts
  packages/workflows/__tests__/api/ListWorkflows.unit.test.ts
  packages/workflows/src/api/ListArchivedWorkflows.ts
  packages/workflows/src/api/ListWorkflows.ts
Labels: release-patch, review

#356 Add encodeURIComponent for wf name string
  packages/workflows/__tests__/api/ListArchivedWorkflows.unit.test.ts
  packages/workflows/__tests__/api/ListWorkflows.unit.test.ts
  packages/workflows/src/api/ListArchivedWorkflows.ts
  packages/workflows/src/api/ListWorkflows.ts
Labels: release-patch, review

#358 Added return code to ssh command
  packages/zosuss/__tests__/__system__/api/Shell.system.test.ts
  packages/zosuss/__tests__/__system__/cli/issue/__data__/exit64.txt
  packages/zosuss/__tests__/__system__/cli/issue/cli.issue.ssh.system.test.ts
  packages/zosuss/__tests__/api/Shell.unit.test.ts
  packages/zosuss/__tests__/cli/issue/ssh/Ssh.definition.unit.test.ts
  packages/zosuss/src/api/Shell.ts
  packages/zosuss/src/cli/issue/ssh/Ssh.definition.ts
  packages/zosuss/src/cli/issue/ssh/Ssh.handler.ts
Labels: release-minor, review

#359 Added return code to ssh command (same as #358)
  packages/zosuss/__tests__/__system__/api/Shell.system.test.ts
  packages/zosuss/__tests__/__system__/cli/issue/__data__/exit64.txt
  packages/zosuss/__tests__/__system__/cli/issue/cli.issue.ssh.system.test.ts
  packages/zosuss/__tests__/api/Shell.unit.test.ts
  packages/zosuss/__tests__/cli/issue/ssh/Ssh.definition.unit.test.ts
  packages/zosuss/src/api/Shell.ts
  packages/zosuss/src/cli/issue/ssh/Ssh.definition.ts
  packages/zosuss/src/cli/issue/ssh/Ssh.handler.ts
Labels: review

#364 Complete Utilites.system.test
  __tests__/__src__/TestUtils.ts
  packages/zosfiles/__tests__/__system__/api/methods/utilities/Utilities.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/utilities/__data__/tagfile.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts
Labels: no-release, review

#373 autocompletion initial commit
  autocompletion/README.md
  autocompletion/zowe.bash
Labels: no-release

#378 remove @zowe registry setting step from README.md
  README.md
Labels: no-release, review

#371 Revised Get method and chtag
  __tests__/__src__/TestUtils.ts
  packages/zosfiles/__tests__/__system__/api/methods/get/Get.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/utilities/Utilities.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/utilities/__data__/tagfile.txt
  packages/zosfiles/__tests__/api/methods/utilities/Utilities.unit.test.ts
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/index.ts
  packages/zosfiles/src/api/methods/download/Download.ts
  packages/zosfiles/src/api/methods/get/Get.ts
  packages/zosfiles/src/api/methods/utilities/Utilities.ts
  packages/zosfiles/src/api/methods/utilities/__data__/tagfile.txt
  packages/zosfiles/src/api/methods/utilities/doc/Tag.ts
  packages/zosfiles/src/api/methods/utilities/index.ts
Labels: release-minor, review

#375 move @types to dev dependencies
  package.json
Labels: release-patch, review

#376 move @types to dev dependencies - lts-incremental
  package.json
Labels: release-patch, review

#379 Fixed using cwd option also returns correct exit code
  packages/zosuss/__tests__/__system__/api/Shell.system.test.ts
  packages/zosuss/__tests__/__system__/cli/issue/cli.issue.ssh.system.test.ts
  packages/zosuss/src/api/Shell.ts
Labels: release-patch, review

#384 Add summary for zowe files upload dir-to-uss
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.definition.ts
Labels: release-patch

#385 Add summary for zowe files upload dir-to-uss
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.definition.ts
Labels: release-patch

#393 fix obsolete snapshot problem by mocking fs.existsSync only once
  package.json
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.handler.unit.test.ts
Labels: no-release, review

#387 add cleanup for start wf system tests
  packages/workflows/__tests__/__system__/cli/start/cli.workflows.start.common.system.test.ts
Labels: no-release

#386 Add cleanup for start workflow system tests
  packages/workflows/__tests__/__system__/cli/start/cli.workflows.start.common.system.test.ts
Labels: no-release

#382 fix broken link Readme > FAQ
  README.md
Labels: no-release, review

#390 remove spaces from alias of instance-variables
  packages/provisioning/__tests__/__integration__/cli/list/instanceVariables/__snapshots__/cli.provisioning.instanceVariables.integration.test.ts.snap
  packages/provisioning/__tests__/cli/list/instanceVars/__snapshots__/InstanceVariables.definition.unit.test.ts.snap
  packages/provisioning/src/cli/list/instanceVariables/InstanceVariables.definition.ts
Labels: no-release, review

#392 Remove spaces from instance variables alias incremental
  packages/provisioning/__tests__/__integration__/cli/list/instanceVariables/__snapshots__/cli.provisioning.instanceVariables.integration.test.ts.snap
  packages/provisioning/__tests__/cli/list/instanceVars/__snapshots__/InstanceVariables.definition.unit.test.ts.snap
  packages/provisioning/src/cli/list/instanceVariables/InstanceVariables.definition.ts
Labels: no-release, review

#381 Revised Get method and chtag - master
  __tests__/__src__/TestUtils.ts
  packages/zosfiles/__tests__/__system__/api/methods/get/Get.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/utilities/Utilities.system.test.ts
  packages/zosfiles/__tests__/api/methods/utilities/Utilities.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.handler.unit.test.ts
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/methods/download/Download.ts
  packages/zosfiles/src/api/methods/get/Get.ts
  packages/zosfiles/src/api/methods/utilities/Utilities.ts
  packages/zosfiles/src/api/methods/utilities/__data__/tagfile.txt
Labels: release-minor, review

#388 List atchived wf api enhance
  packages/workflows/__tests__/__system__/api/ListArchivedWorkflows.system.test.ts
  packages/workflows/__tests__/api/ListArchivedWorkflows.unit.test.ts
  packages/workflows/__tests__/cli/delete/deleteArchivedWorkflow/Delete.archived.common.handler.unit.test.ts
  packages/workflows/src/api/ListArchivedWorkflows.ts
  packages/workflows/src/cli/delete/Delete.archived.common.handler.ts
Labels: release-patch

#402 update readme file and create CLI Ref PDF
  docs/CLIReadme.md
Labels: no-release

#399 Allow users to delete multiple workflows using workflow name with wildcard
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__snapshots__/cli.workflows.delete.activeworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/delete/__snapshots__/cli.workflows.delete.common.system.test.ts.snap
  packages/workflows/__tests__/__system__/cli/delete/cli.workflows.delete.common.system.test.ts
  packages/workflows/__tests__/cli/delete/Delete.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/delete/__snapshots__/Delete.common.handler.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/deleteActiveWorkflow/__snapshots__/deleteActiveWorkflow.definition.unit.test.ts.snap
  packages/workflows/src/cli/delete/Delete.common.handler.ts
  packages/workflows/src/cli/delete/deleteActiveWorkflow/DeleteActiveWorkflow.definition.ts
Labels: release-minor

#403 Fix command examples with input piped in
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/upload/stds/__snapshots__/cli.files.upload.stds.integration.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/stds/__snapshots__/StdinToDataSet.definition.unit.test.ts.snap
  packages/zosfiles/src/cli/upload/stds/StdinToDataSet.definition.ts
Labels: release-patch

#404 (lts-incremental) Fix command examples with input piped in
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/upload/stds/__snapshots__/cli.files.upload.stds.integration.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/stds/__snapshots__/StdinToDataSet.definition.unit.test.ts.snap
  packages/zosfiles/src/cli/upload/stds/StdinToDataSet.definition.ts
Labels: release-patch

#405 Lts delete archived wildcard
  packages/workflows/__tests__/__integration__/cli/delete/archivedWorkflow/__snapshots__/cli.workflows.delete.archivedworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/deleteArchived/cli.workflows.delete.common.system.test.ts
  packages/workflows/__tests__/cli/delete/deleteArchivedWorkflow/Delete.archived.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/delete/deleteArchivedWorkflow/__snapshots__/Delete.archived.common.handler.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/deleteArchivedWorkflow/__snapshots__/deleteArchivedWorkflow.definition.unit.test.ts.snap
  packages/workflows/src/cli/delete/Delete.archived.common.handler.ts
  packages/workflows/src/cli/delete/deleteArchivedWorkflow/DeleteArchivedWorkflow.definition.ts
Labels: release-minor

#418 Add USS rename functionality
  packages/zosfiles/__tests__/__system__/api/methods/utilities/Utilities.system.test.ts
  packages/zosfiles/__tests__/api/methods/utilities/Utilities.unit.test.ts
  packages/zosfiles/src/api/methods/utilities/Utilities.ts
Labels: release-minor
