Repository zowe/zowe-cli, pull requests merged in 2019-04, with the labels that each got.

#310 API to list systems defined to zosmf
  packages/zosmf/__tests__/__system__/api/methods/ListDefinedSystems.system.test.ts
  packages/zosmf/__tests__/api/methods/ListDefinedSystems.unit.test.ts
  packages/zosmf/src/api/constants/Zosmf.constants.ts
  packages/zosmf/src/api/doc/IDefinedSystem.ts
  packages/zosmf/src/api/doc/IZosmfListDefinedSystemsResponse.ts
  packages/zosmf/src/api/index.ts
  packages/zosmf/src/api/methods/ListDefinedSystems.ts
Labels: release-minor

#311 Step summary only option
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__scripts__/command/list_active_workflow_details_ls_and_sso.sh
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__scripts__/command/list_active_workflow_details_sws.sh
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__snapshots__/cli.workflows.list.activeWorkflowDetails.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/cli.workflows.list.activeWorkflowDetails.integration.test.ts
  packages/workflows/__tests__/cli/list/activeWorkflowDetails/__snapshots__/ActiveWorkflowDetails.definition.unit.test.ts.snap
  packages/workflows/src/api/Properties.ts
  packages/workflows/src/api/doc/IStepSummary.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.common.options.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.definition.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.handler.ts
Labels: release-minor, review

#319 Rework hanndler to properly accept workflow-name option
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.handler.ts
Labels: release-patch

#316 add list defindes zosmf systems
  packages/zosmf/__tests__/__system__/api/methods/ListDefinedSystems.system.test.ts
  packages/zosmf/__tests__/api/methods/ListDefinedSystems.unit.test.ts
  packages/zosmf/src/api/constants/Zosmf.constants.ts
  packages/zosmf/src/api/doc/IDefinedSystem.ts
  packages/zosmf/src/api/doc/IZosmfListDefinedSystemsResponse.ts
  packages/zosmf/src/api/index.ts
  packages/zosmf/src/api/methods/ListDefinedSystems.ts
Labels: release-minor, review

#318 Rework hanndler to properly accept workflow-name option
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.handler.ts
Labels: release-patch, review

#322 Updated description of overwrite (create workflow CLI) - master branch
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/src/api/Create.ts
  packages/workflows/src/cli/create/Create.common.options.ts
Labels: release-patch, review

#315 Updated description of overwrite (create workflow CLI)
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/src/api/Create.ts
  packages/workflows/src/cli/create/Create.common.options.ts
Labels: release-patch, review

#327 Fix #320, ctrl+clicking on doc links in lts-incremental
  docs/CLIReadme.md
  packages/Constants.ts
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
Labels: release-patch, review

#323 Resolve issue #320
  docs/CLIReadme.md
  package.json
  packages/Constants.ts
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
Labels: release-patch, review

#329 Port changes introduced to lts-incremental via #311
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__scripts__/command/list_active_workflow_details_ls_and_sso.sh
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__scripts__/command/list_active_workflow_details_sws.sh
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__snapshots__/cli.workflows.list.activeWorkflowDetails.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/cli.workflows.list.activeWorkflowDetails.integration.test.ts
  packages/workflows/__tests__/cli/list/activeWorkflowDetails/__snapshots__/ActiveWorkflowDetails.definition.unit.test.ts.snap
  packages/workflows/src/api/Properties.ts
  packages/workflows/src/api/doc/IStepSummary.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.common.options.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.definition.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.handler.ts
Labels: release-minor

#331 Use new streaming RestClient APIs to reduce memory usage when downloading and uploading files
  package.json
  packages/workflows/__tests__/__system__/Archive.system.test.ts
  packages/workflows/__tests__/__system__/Cancel.system.test.ts
  packages/workflows/__tests__/__system__/api/ArchivedDelete.system.test.ts
  packages/workflows/__tests__/__system__/api/Delete.system.test.ts
  packages/workflows/__tests__/__system__/api/ListArchivedWorkflows.system.test.ts
  packages/workflows/__tests__/__system__/api/ListWorkflows.system.test.ts
  packages/workflows/__tests__/__system__/api/Properties.system.test.ts
  packages/workflows/__tests__/__system__/api/Start.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/download/Download.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/get/Get.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/create/binaryPds/__snapshots__/cli.files.create.dataset.binary.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/create/cPds/__snapshots__/cli.files.create.dataset.c.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/create/classicPds/__snapshots__/cli.files.create.dataset.classic.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/create/pds/__snapshots__/cli.files.create.dataset.pds.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/create/ps/__snapshots__/cli.files.create.dataset.ps.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/create/vsam/cli.files.create.dataset.vsam.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/delete/ds/__snapshots__/cli.files.delete.ds.system.test.ts.snap
  packages/zosfiles/__tests__/__system__/cli/download/uss/cli.files.download.uss.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts
  packages/zosfiles/__tests__/api/methods/download/Download.unit.test.ts
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
  packages/zosfiles/__tests__/cli/download/ds/Dataset.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/download/uss/UssFile.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/ftds/FileToDataSet.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/ftds/__snapshots__/FileToDataSet.handler.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/ftu/FileToUSS.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/stds/StdinToDataSet.handler.unit.test.ts
  packages/zosfiles/src/api/methods/download/Download.ts
  packages/zosfiles/src/api/methods/get/Get.ts
  packages/zosfiles/src/api/methods/get/doc/IGetOptions.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadOptions.ts
  packages/zosfiles/src/cli/download/ds/Dataset.handler.ts
  packages/zosfiles/src/cli/download/uss/UssFile.handler.ts
  packages/zosfiles/src/cli/upload/ftds/FileToDataSet.handler.ts
  packages/zosfiles/src/cli/upload/ftu/FileToUSS.handler.ts
  packages/zosfiles/src/cli/upload/stds/StdinToDataSet.handler.ts
  packages/zosjobs/__tests__/__system__/api/DownloadJobs.system.test.ts
  packages/zosjobs/__tests__/__system__/api/SubmitJobs.system.test.ts
  packages/zosjobs/__tests__/__system__/cli/submit/local-file/testFileOfLocalJCL.txt
  packages/zosjobs/__tests__/api/DownloadJobs.unit.test.ts
  packages/zosjobs/src/api/DownloadJobs.ts
  packages/zosjobs/src/api/GetJobs.ts
  packages/zosmf/__tests__/__system__/api/methods/CheckStatus.system.test.ts
Labels: release-major, review

#335 move vulnerability check later in the build so that the tests can still run if the vulnerability check fails
  Jenkinsfile
Labels: review

#336 move check for vulnerabilities to later in the build (lts-incremental)
  Jenkinsfile
Labels: review

#343 fix #313 - lts-incremental
  packages/zosfiles/__tests__/__system__/api/methods/delete/DeleteUSSFile.system.test.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/utils/ZosFilesUtils.ts
Labels: release-patch, review

#341 Fix #313
  packages/zosfiles/__tests__/__system__/api/methods/delete/DeleteUSSFile.system.test.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/utils/ZosFilesUtils.ts
Labels: release-patch, review
