Repository zowe/zowe-cli, pull requests merged in 2019-06, with the labels that each got.

#426 Port PR 399 to master
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__snapshots__/cli.workflows.delete.activeworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/delete/cli.workflows.delete.common.system.test.ts
  packages/workflows/__tests__/cli/delete/Delete.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/delete/__snapshots__/Delete.common.handler.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/deleteActiveWorkflow/__snapshots__/deleteActiveWorkflow.definition.unit.test.ts.snap
  packages/workflows/src/cli/delete/Delete.common.handler.ts
  packages/workflows/src/cli/delete/deleteActiveWorkflow/DeleteActiveWorkflow.definition.ts
Labels: release-minor

#428 Fix Upload.unit on windows
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
Labels: no-release

#447 fix vulns
  .gitignore
  .npmrc
  Jenkinsfile
  package-lock.json
  package.json
Labels: release-patch

#427 Fix Upload.unit on Windows (lts-incremental)
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
Labels: no-release

#448 fix vulns
  .gitignore
  npm-shrinkwrap.json
  package-lock.json
  package.json
Labels: release-patch

#438 Introduce changes from conformance branch
  CONTRIBUTING.md
  README.md
  docs/CommandFormatStandards.md
  docs/MaintainerVersioning.md
  docs/PackagesAndPluginGuidelines.md
  docs/PluginTESTINGGuidelines.md
  docs/ProfileGuidelines.md
  docs/TESTING.md
Labels: cli, documentation, no-release

#450 #440 Examples for zowe files list uss-files are slightly incorrect
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__snapshots__/cli.files.list.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap
  packages/zosfiles/src/cli/list/uss/UssFile.definition.ts
Labels: release-patch

#452 Added homepage and bugs values to package.json
  package.json
Labels: release-patch

#453 Update for issue #440
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__snapshots__/cli.files.list.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap
  packages/zosfiles/src/cli/list/uss/UssFile.definition.ts
Labels: release-patch

#454 Port changes from #435
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__snapshots__/cli.workflows.archive.workflow.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/archive/workflow/cli.workflows.archive.workflow.system.test.ts
  packages/workflows/__tests__/cli/archive/workflow/Archive.workflow.handler.unit.test.ts
  packages/workflows/__tests__/cli/archive/workflow/__snapshots__/Archive.workflow.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/archive/workflow/__snapshots__/Archive.workflow.handler.unit.test.ts.snap
  packages/workflows/src/cli/archive/Archive.handler.ts
  packages/workflows/src/cli/archive/workflow/Archive.workflow.definition.ts
Labels: release-minor

#465 Correct incremental readme - install from source
  README.md
Labels: cli, documentation, no-release

#466 Fix snapshots imperative help update
  package-lock.json
  package.json
  packages/provisioning/__tests__/__integration__/cli/delete/__snapshots__/cli.provisioning.delete.instance.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/list/catalogTemplates/__snapshots__/cli.provisioning.catalogTemplates.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/list/instanceInfo/__snapshots__/cli.provisioning.instanceInfo.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/list/instanceVariables/__snapshots__/cli.provisioning.instanceVariables.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/list/registryInstances/__snapshots__/cli.provisioning.registryInstances.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/list/templateInfo/__snapshots__/cli.provisioning.templateInfo.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/perform/__snapshots__/cli.provisioning.perform.action.integration.test.ts.snap
  packages/provisioning/__tests__/__integration__/cli/provision/__snapshots__/cli.provisioning.provision.template.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/archive/workflow/__snapshots__/cli.workflows.archive.workflow.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/localfile/__snapshots__/cli.workflows.create.workflowLocalFile.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__snapshots__/cli.workflows.delete.activeworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/delete/archivedWorkflow/__snapshots__/cli.workflows.delete.archivedworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__snapshots__/cli.workflows.list.activeWorkflowDetails.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflows/__snapshots__/cli.workflows.list.activeWorkflows.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/retrieveWorkflowDefinition/__snapshots__/cli.workflows.list.retrieveWorkflowDefiinition.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__snapshots__/cli.workflows.start.workflowFull.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__snapshots__/cli.workflows.start.workflowStep.integration.test.ts.snap
  packages/zosconsole/__tests__/__integration__/cli/collect/__snapshots__/cli.zos-console.collect.response.integration.test.ts.snap
  packages/zosconsole/__tests__/__integration__/cli/issue/__snapshots__/cli.zos-console.issue.command.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/create/binaryPds/__snapshots__/cli.files.create.dataset.binary.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/create/cPds/__snapshots__/cli.files.create.dataset.c.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/create/classicPds/__snapshots__/cli.files.create.dataset.classic.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/create/ps/__snapshots__/cli.files.create.dataset.ps.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/create/vsam/__snapshots__/cli.files.create.dataset.vsam.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/delete/ds/__snapshots__/cli.files.delete.ds.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/delete/uss/__snapshots__/cli.files.delete.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/delete/vsam/__snapshots__/cli.files.delete.vsam.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/download/am/__snapshots__/cli.files.download.am.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/download/ds/__snapshots__/cli.files.download.ds.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/download/uss/__snapshots__/cli.files.download.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/invoke/amsFile/__snapshots__/cli.files.invoke.amsFile.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/invoke/amsStatements/__snapshots__/cli.files.invoke.amsStatements.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/list/am/__snapshots__/cli.files.list.am.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/list/ds/__snapshots__/cli.files.list.ds.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__snapshots__/cli.files.list.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtp/__snapshots__/cli.files.upload.dtp.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__snapshots__/cli.files.upload.dtu.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/ftds/__snapshots__/cli.files.upload.ftds.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/ftu/__snapshots__/cli.files.upload.ftu.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/stds/__snapshots__/cli.files.upload.stds.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/cancel/__snapshots__/cli.zos-jobs.cancel.job.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/delete/__snapshots__/cli.zos-jobs.delete.job.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/download/__snapshots__/cli.zos-jobs.download.output.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/list/__snapshots__/cli.zos-jobs.list.spool-files-by-jobid.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/submit/data-set/__snapshots__/cli.zos-jobs.submit.data-set.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/view/__snapshots__/cli.zos-jobs.view.job-status-by-jobid.integration.test.ts.snap
  packages/zosjobs/__tests__/__integration__/cli/view/__snapshots__/cli.zos-jobs.view.spool-file-by-id.integration.test.ts.snap
  packages/zosmf/__tests__/__integration__/cli/check/__snapshots__/zosmf.check.status.integration.test.ts.snap
  packages/zosmf/__tests__/__integration__/cli/list/__snapshots__/zosmf.list.systems.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/issue/__snapshots__/cli.zos-tso.issue.cmd.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/ping/__snapshots__/cli.zos-tso.ping.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/send/__snapshots__/cli.zos-tso.send.as.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/start/__snapshots__/cli.zos-tso.start.address-space.integration.test.ts.snap
  packages/zostso/__tests__/__integration__/cli/stop/__snapshots__/cli.zos-tso.stop.address-space.integration.test.ts.snap
  packages/zosuss/__tests__/__integration__/cli/issue/__snapshots__/cli.zos-uss.issue.ssh.integration.test.ts.snap
Labels: release-patch

#464 Correct Readme - install from source
  README.md
Labels: cli, documentation, no-release

#459 fix links
  CONTRIBUTING.md
  docs/PackagesAndPluginGuidelines.md
Labels: cli, documentation, no-release
