Repository zowe/zowe-cli, pull requests merged in 2019-03, with the labels that each got.

#254 Update create wf cli, move tests
  packages/workflows/__tests__/__integration__/cli/create/dataset/__scripts__/command/command_create_workflow_ds_empty.sh
  packages/workflows/__tests__/__integration__/cli/create/dataset/__scripts__/create_workflow_ds_help.sh
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/dataset/cli.workflows.create.workflowDs.integration.test.ts
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__scripts__/command/command_create_workflow_uss_empty.sh
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__scripts__/create_workflow_uss_help.sh
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/cli.workflows.create.workflowUss.integration.test.ts
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__scripts__/command/command_delete_workflow_key.sh
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__scripts__/delete_active_workflow_help.sh
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/__snapshots__/cli.workflows.delete.activeworkflow.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/delete/activeWorkflow/cli.workflows.delete.activeworkflow.integration.test.ts
  packages/workflows/__tests__/__system__/cli/create/__snapshots__/cli.workflows.create.common.system.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/cli.workflows.create.common.system.test.ts
  packages/workflows/__tests__/__system__/cli/delete/cli.workflows.delete.common.system.test.ts
  packages/workflows/__tests__/__system__/testfiles/demods.xml
  packages/workflows/src/cli/create/Create.common.handler.ts
Labels: release-patch

#259 Update LICENSE
  LICENSE
Labels: release-patch, review

#257 Archived Delete API
  packages/workflows/__tests__/__system__/api/ArchivedDelete.system.test.ts
  packages/workflows/__tests__/api/ArchivedDelete.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/ArchivedDelete.ts
  packages/workflows/src/api/WorkflowConstants.ts
Labels: release-minor, review

#258 Workflows/fix/remove DS check
  packages/workflows/__tests__/__system__/api/Create.system.test.ts
  packages/workflows/__tests__/api/Create.unit.test.ts
  packages/workflows/src/api/Create.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/WorkflowValidator.ts
Labels: release-patch

#263 Cli text improvement
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflows/__snapshots__/cli.workflows.list.activeWorkflows.integration.test.ts.snap
  packages/workflows/__tests__/cli/__snapshots__/Workflows.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/__snapshots__/Create.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/delete/__snapshots__/Delete.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/list/__snapshots__/List.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/list/activeWorkflow/__snapshots__/ActiveWorkflows.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/__snapshots__/Start.definition.unit.test.ts.snap
  packages/workflows/src/cli/Workflows.definition.ts
  packages/workflows/src/cli/create/Create.common.options.ts
  packages/workflows/src/cli/create/Create.definition.ts
  packages/workflows/src/cli/create/dataset/Dataset.definition.ts
  packages/workflows/src/cli/create/ussfile/UssFile.definition.ts
  packages/workflows/src/cli/delete/Delete.definition.ts
  packages/workflows/src/cli/list/List.definition.ts
  packages/workflows/src/cli/list/activeWorkflows/ActiveWorkflows.options.ts
  packages/workflows/src/cli/start/Start.definition.ts
Labels: release-patch, review

#262 zos-workflows review
  packages/workflows/__tests__/__integration__/cli/list/activeWorkflowDetails/__snapshots__/cli.workflows.list.activeWorkflowDetails.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__snapshots__/cli.workflows.start.workflowFull.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__snapshots__/cli.workflows.start.workflowStep.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/cli.workflows.create.common.system.test.ts
  packages/workflows/__tests__/__system__/cli/start/cli.workflows.start.common.system.test.ts
  packages/workflows/__tests__/cli/create/Create.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/create/__snapshots__/Create.common.handler.unit.test.ts.snap
  packages/workflows/__tests__/cli/list/activeWorkflowDetails/__snapshots__/ActiveWorkflowDetails.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/workflowFull/WorkflowFull.handler.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowFull/__snapshots__/WorkflowFull.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/workflowStep/__snapshots__/WorkflowStep.definition.unit.test.ts.snap
  packages/workflows/src/cli/create/Create.common.handler.ts
  packages/workflows/src/cli/list/activeWorkflowDetails/ActiveWorkflowDetails.definition.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.definition.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.handler.ts
  packages/workflows/src/cli/start/workflowStep/WorkflowStep.definition.ts
Labels: release-patch, review

#261 253 uss list
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__scripts__/command/command_list_uss.sh
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__scripts__/command_list_uss_help.sh
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__snapshots__/cli.files.list.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/list/uss/cli.files.list.uss.integration.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/list/List.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/list/uss/__scripts__/command/command_list_uss.sh
  packages/zosfiles/__tests__/__system__/cli/list/uss/__scripts__/command/command_list_uss_fully_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/list/uss/cli.files.list.uss.system.test.ts
  packages/zosfiles/__tests__/api/methods/list/List.unit.test.ts
  packages/zosfiles/__tests__/cli/list/ds/Dataset.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/Uss.definition.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/Uss.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.handler.unit.test.ts.snap
  packages/zosfiles/src/api/constants/ZosFiles.constants.ts
  packages/zosfiles/src/api/doc/IUSSFileListResponse.ts
  packages/zosfiles/src/api/methods/list/List.ts
  packages/zosfiles/src/api/methods/list/doc/IUSSListOptions.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/list/List.definition.ts
  packages/zosfiles/src/cli/list/uss/UssFile.definition.ts
  packages/zosfiles/src/cli/list/uss/UssFile.handler.ts
Labels: release-minor, review

#272 correct key for solicited keyword option on console issue command - lts-incremental
  package.json
  packages/zosconsole/__tests__/ConsoleValidator.unit.test.ts
  packages/zosconsole/__tests__/IssueCommand.unit.test.ts
  packages/zosconsole/__tests__/__system__/cli/issue/__scripts__/command/command_solkey.sh
  packages/zosconsole/__tests__/__system__/cli/issue/cli.zos-console.issue.command.system.test.ts
  packages/zosconsole/src/api/IssueCommand.ts
  packages/zosconsole/src/api/doc/zosmf/IZosmfIssueParms.ts
Labels: release-patch, review

#271 correct key for solicited keyword option on console issue command - fix #270
  package.json
  packages/zosconsole/__tests__/ConsoleValidator.unit.test.ts
  packages/zosconsole/__tests__/IssueCommand.unit.test.ts
  packages/zosconsole/__tests__/__system__/cli/issue/__scripts__/command/command_solkey.sh
  packages/zosconsole/__tests__/__system__/cli/issue/cli.zos-console.issue.command.system.test.ts
  packages/zosconsole/src/api/IssueCommand.ts
  packages/zosconsole/src/api/doc/zosmf/IZosmfIssueParms.ts
Labels: release-patch, review

#273 253 lts incremental
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__scripts__/command/command_list_uss.sh
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__scripts__/command_list_uss_help.sh
  packages/zosfiles/__tests__/__integration__/cli/list/uss/__snapshots__/cli.files.list.uss.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/list/uss/cli.files.list.uss.integration.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/list/List.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/list/uss/__scripts__/command/command_list_uss.sh
  packages/zosfiles/__tests__/__system__/cli/list/uss/__scripts__/command/command_list_uss_fully_qualified.sh
  packages/zosfiles/__tests__/__system__/cli/list/uss/cli.files.list.uss.system.test.ts
  packages/zosfiles/__tests__/api/methods/list/List.unit.test.ts
  packages/zosfiles/__tests__/cli/list/ds/Dataset.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/Uss.definition.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/Uss.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.definition.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/list/uss/__snapshots__/Uss.handler.unit.test.ts.snap
  packages/zosfiles/src/api/constants/ZosFiles.constants.ts
  packages/zosfiles/src/api/doc/IUSSFileListResponse.ts
  packages/zosfiles/src/api/methods/list/List.ts
  packages/zosfiles/src/api/methods/list/doc/IUSSListOptions.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/list/List.definition.ts
  packages/zosfiles/src/cli/list/uss/UssFile.definition.ts
  packages/zosfiles/src/cli/list/uss/UssFile.handler.ts
Labels: review

#274 fix sol-key issue in lts-stable
  packages/zosconsole/__tests__/ConsoleValidator.unit.test.ts
  packages/zosconsole/__tests__/IssueCommand.unit.test.ts
  packages/zosconsole/__tests__/__system__/cli/issue/__scripts__/command/command_solkey.sh
  packages/zosconsole/__tests__/__system__/cli/issue/cli.zos-console.issue.command.system.test.ts
  packages/zosconsole/src/api/IssueCommand.ts
  packages/zosconsole/src/api/doc/zosmf/IZosmfIssueParms.ts
Labels: release-patch, review

#287 Fix typo in definition, update snaps
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/src/cli/create/dataset/Dataset.definition.ts
Labels: release-patch

#278 Enhance start cli
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/command/command_start_workflow_both.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/command/command_start_workflow_empty.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/command/command_start_workflow_key_full.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__scripts__/command/command_start_workflow_name_full.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/__snapshots__/cli.workflows.start.workflowFull.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowFull/cli.workflows.start.workflowFull.integration.test.ts
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/command/command_start_workflow_both.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/command/command_start_workflow_empty.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/command/command_start_workflow_key_step.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__scripts__/command/command_start_workflow_name_step.sh
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/__snapshots__/cli.workflows.start.workflowStep.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/start/workflowStep/cli.workflows.start.workflowStep.integration.test.ts
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_key_full.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_key_step.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_key_step_plus_following.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_name_full.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_name_step.sh
  packages/workflows/__tests__/__system__/cli/start/__scripts__/command/command_start_workflow_name_step_plus_following.sh
  packages/workflows/__tests__/__system__/cli/start/cli.workflows.start.common.system.test.ts
  packages/workflows/__tests__/cli/start/workflowFull/WorkflowFull.handler.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowFull/__snapshots__/WorkflowFull.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/start/workflowStep/WorkflowStep.handler.unit.test.ts
  packages/workflows/__tests__/cli/start/workflowStep/__snapshots__/WorkflowStep.definition.unit.test.ts.snap
  packages/workflows/src/cli/start/Start.common.options.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.definition.ts
  packages/workflows/src/cli/start/workflowFull/WorkflowFull.handler.ts
  packages/workflows/src/cli/start/workflowStep/WorkflowStep.definition.ts
  packages/workflows/src/cli/start/workflowStep/WorkflowStep.handler.ts
Labels: release-minor, review

#245 Fix/204
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/download/am/__snapshots__/cli.files.download.am.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__scripts__/command_upload_dtu_help.sh
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__snapshots__/cli.files.upload.dtu.integration.test.ts.snap
  packages/zosfiles/__tests__/__system__/api/methods/upload/Upload.system.test.ts
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts
  packages/zosfiles/__tests__/api/methods/download/Download.unit.test.ts
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
  packages/zosfiles/__tests__/cli/download/am/__snapshots__/AllMembers.definition.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/__snapshots__/DirToUSS.definition.unit.test.ts.snap
  packages/zosfiles/src/api/methods/create/Create.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/api/methods/get/Get.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadDir.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadFile.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadOptions.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/upload/Upload.options.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.definition.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.handler.ts
Labels: release-minor, review

#290 Workflow definition API for Incremental branch merge
  packages/workflows/__tests__/__system__/api/Definition.system.test.ts
  packages/workflows/__tests__/api/Definition.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/Definition.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/doc/IPropertyMapping.ts
  packages/workflows/src/api/doc/IStepApprovers.ts
  packages/workflows/src/api/doc/IStepDefinition.ts
  packages/workflows/src/api/doc/IVariableDefinition.ts
  packages/workflows/src/api/doc/IVariableSpecification.ts
  packages/workflows/src/api/doc/IWorkflowDefinition.ts
Labels: release-minor

#291 Workflow definition API for Master branch merge
  packages/workflows/__tests__/__system__/api/Definition.system.test.ts
  packages/workflows/__tests__/api/Definition.unit.test.ts
  packages/workflows/index.ts
  packages/workflows/src/api/Definition.ts
  packages/workflows/src/api/WorkflowConstants.ts
  packages/workflows/src/api/doc/IPropertyMapping.ts
  packages/workflows/src/api/doc/IStepApprovers.ts
  packages/workflows/src/api/doc/IStepDefinition.ts
  packages/workflows/src/api/doc/IVariableDefinition.ts
  packages/workflows/src/api/doc/IVariableSpecification.ts
  packages/workflows/src/api/doc/IWorkflowDefinition.ts
Labels: release-minor, review

#284 Resolve SHARE issue
  package.json
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
  packages/provisioning/__tests__/cli/__snapshots__/Provisioning.definition.unit.test.ts.snap
  packages/provisioning/src/cli/Provisioning.definition.ts
  packages/workflows/__tests__/cli/__snapshots__/Workflows.definition.unit.test.ts.snap
  packages/workflows/src/cli/Workflows.definition.ts
  packages/zostso/__tests__/cli/__snapshots__/ZosTso.definition.unit.test.ts.snap
  packages/zostso/src/cli/ZosTso.definition.ts
Labels: review

#293 Overwrite option in Create workflow CLI - master
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_ds.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_uss.sh
  packages/workflows/__tests__/__system__/cli/create/cli.workflows.create.common.system.test.ts
  packages/workflows/__tests__/cli/create/Create.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/src/cli/create/Create.common.handler.ts
  packages/workflows/src/cli/create/Create.common.options.ts
  packages/workflows/src/cli/create/dataset/Dataset.definition.ts
  packages/workflows/src/cli/create/ussfile/UssFile.definition.ts
Labels: release-minor, review

#292 Overwrite option create cli
  packages/workflows/__tests__/__integration__/cli/create/dataset/__snapshots__/cli.workflows.create.workflowDs.integration.test.ts.snap
  packages/workflows/__tests__/__integration__/cli/create/ussfile/__snapshots__/cli.workflows.create.workflowUss.integration.test.ts.snap
  packages/workflows/__tests__/__system__/cli/List/activeWorkflowDetails/cli.workflows.list.active.details.system.test.ts
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_ds.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_ds_empty.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_uss.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/command/command_create_workflow_uss_empty.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/create_workflow_ds_help.sh
  packages/workflows/__tests__/__system__/cli/create/__scripts__/create_workflow_uss_help.sh
  packages/workflows/__tests__/__system__/cli/create/__snapshots__/cli.workflows.create.common.system.test.ts.snap
  packages/workflows/__tests__/__system__/cli/create/cli.workflows.create.common.system.test.ts
  packages/workflows/__tests__/cli/create/Create.common.handler.unit.test.ts
  packages/workflows/__tests__/cli/create/dataset/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/workflows/__tests__/cli/create/ussfile/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/workflows/src/cli/create/Create.common.handler.ts
  packages/workflows/src/cli/create/Create.common.options.ts
  packages/workflows/src/cli/create/dataset/Dataset.definition.ts
  packages/workflows/src/cli/create/ussfile/UssFile.definition.ts
Labels: release-minor

#294 lts-incremental update
  docs/CLIReadme.md
  packages/zosfiles/__tests__/__integration__/cli/download/am/__snapshots__/cli.files.download.am.integration.test.ts.snap
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__scripts__/command_upload_dtu_help.sh
  packages/zosfiles/__tests__/__integration__/cli/upload/dtu/__snapshots__/cli.files.upload.dtu.integration.test.ts.snap
  packages/zosfiles/__tests__/__system__/api/methods/upload/Upload.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/upload/testfiles/space dir/file4.txt
  packages/zosfiles/__tests__/__system__/cli/upload/dtu/cli.dir.upload.dtu.system.test.ts
  packages/zosfiles/__tests__/api/methods/download/Download.unit.test.ts
  packages/zosfiles/__tests__/api/methods/upload/Upload.unit.test.ts
  packages/zosfiles/__tests__/cli/download/am/__snapshots__/AllMembers.definition.unit.test.ts.snap
  packages/zosfiles/__tests__/cli/upload/dtu/DirToUSS.handler.unit.test.ts
  packages/zosfiles/__tests__/cli/upload/dtu/__snapshots__/DirToUSS.definition.unit.test.ts.snap
  packages/zosfiles/src/api/methods/create/Create.ts
  packages/zosfiles/src/api/methods/delete/Delete.ts
  packages/zosfiles/src/api/methods/get/Get.ts
  packages/zosfiles/src/api/methods/upload/Upload.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadDir.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadFile.ts
  packages/zosfiles/src/api/methods/upload/doc/IUploadOptions.ts
  packages/zosfiles/src/cli/-strings-/en.ts
  packages/zosfiles/src/cli/upload/Upload.options.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.definition.ts
  packages/zosfiles/src/cli/upload/dtu/DirToUSSDir.handler.ts
Labels: release-minor, review

#295 fix system test for files upload dtu api
  packages/zosfiles/__tests__/__system__/api/methods/upload/Upload.system.test.ts
  packages/zosfiles/__tests__/__system__/api/methods/upload/testfiles/space dir/file4.txt
Labels: review

#296 update top level help summaries - port changes from #284 to lts-incremental
  package.json
  packages/help/__tests__/__integration__/__snapshots__/BrightHelpTests.integration.test.ts.snap
  packages/provisioning/__tests__/cli/__snapshots__/Provisioning.definition.unit.test.ts.snap
  packages/provisioning/src/cli/Provisioning.definition.ts
  packages/workflows/__tests__/cli/__snapshots__/Workflows.definition.unit.test.ts.snap
  packages/workflows/src/cli/Workflows.definition.ts
  packages/zostso/__tests__/cli/__snapshots__/ZosTso.definition.unit.test.ts.snap
  packages/zostso/src/cli/ZosTso.definition.ts
Labels: release-patch, review

#300 Fixed vulnerabilities
  package.json
Labels: review
