Repository zowe/zowe-cli, pull requests merged in 2020-09, with the labels that each got.

#807 Add contributor guidelines for SDK development
  docs/SDKGuidelines.md
Labels: documentation, no-changelog

#812 785 lint lerna packages
  package-lock.json
  package.json
  packages/auth/package.json
  packages/cli/__tests__/provisioning/__system__/list/catalogTemplates/__tests__/__results__/junit.xml
  packages/cli/package.json
  packages/cli/src/provisioning/delete/instance/DeleteInstance.handler.ts
  packages/cli/src/provisioning/list/catalogTemplates/CatalogTemplates.handler.ts
  packages/cli/src/provisioning/list/instanceVariables/InstanceVariables.handler.ts
  packages/cli/src/provisioning/list/templateInfo/TemplateInfo.handler.ts
  packages/cli/src/provisioning/perform/action/Action.handler.ts
  packages/cli/src/provisioning/provision/template/Template.handler.ts
  packages/cli/src/workflows/create/Create.common.handler.ts
  packages/cli/src/workflows/delete/Delete.archived.common.handler.ts
  packages/cli/src/workflows/start/workflowFull/WorkflowFull.handler.ts
  packages/provisioning/package.json
  packages/rest/package.json
  packages/utils/package.json
  packages/workflows/__tests__/__system__/api/ListWorkflows.system.test.ts
  packages/workflows/package.json
  packages/zosconsole/package.json
  packages/zosfiles/__tests__/__system__/methods/upload/Upload.system.test.ts
  packages/zosfiles/package.json
  packages/zosfiles/src/index.ts
  packages/zosfiles/src/methods/copy/Copy.ts
  packages/zosfiles/src/utils/ZosFilesUtils.ts
  packages/zosjobs/package.json
  packages/zosmf/package.json
  packages/zostso/package.json
  packages/zosuss/__tests__/__unit__/Shell.unit.test.ts
  packages/zosuss/package.json
  packages/zosuss/src/index.ts
Labels: no-changelog

#809 Update readme for SDK
  README.md
Labels: cli, documentation, no-changelog
