Repository zowe/zowe-cli, pull requests merged in 2020-07, with the labels that each got.

#768 Describe Node APIs in Readme
  CHANGELOG.md
  README.md
Labels: cli, documentation

#758 GitHub Actions
  .github/workflows/audit.yml
  .github/workflows/changelog.yml
  .github/workflows/linter.yml
  .github/workflows/zowe-cli.yml
  Jenkinsfile
Labels: no-changelog

#766 Implementation of new "like" parameter for data set creation
  CHANGELOG.md
  package-lock.json
  packages/zosfiles/__tests__/__system__/api/methods/create/Create.system.test.ts
  packages/zosfiles/__tests__/api/methods/create/Create.unit.test.ts
  packages/zosfiles/src/api/constants/ZosFiles.messages.ts
  packages/zosfiles/src/api/methods/create/Create.ts
Labels: 20PI3
