Repository zowe/zowe-cli, pull requests merged in 2020-10, with the labels that each got.

#830 Edit changelog entry
  CHANGELOG.md
Labels: cli, documentation, no-changelog

#844 Move version from package.json to lerna.json
  lerna.json
  package-lock.json
  package.json
Labels: no-changelog

#845 Remove Imperative peer dependencies from SDKs
  package-lock.json
  packages/cli/package-lock.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/provisioning/package-lock.json
  packages/provisioning/package.json
  packages/workflows/package-lock.json
  packages/workflows/package.json
  packages/zosconsole/package-lock.json
  packages/zosconsole/package.json
  packages/zosfiles/package-lock.json
  packages/zosfiles/package.json
  packages/zosjobs/package-lock.json
  packages/zosjobs/package.json
  packages/zosmf/package-lock.json
  packages/zosmf/package.json
  packages/zostso/package-lock.json
  packages/zostso/package.json
  packages/zosuss/package-lock.json
  packages/zosuss/package.json
  tslint-packages.json
Labels: no-changelog

#846 Report actual project version to SonarCloud
  Jenkinsfile
  sonar-project.properties
Labels: no-changelog

#848 Add task to build typedoc for Zowe Node.js SDK
  gulp/DevelopmentTasks.ts
  gulpfile.js
  package.json
  typedoc.json
Labels: no-changelog, no-release

#849 Remove readme from SDK typedoc
  packages/cli/README.md
  typedoc.json
Labels: no-changelog, no-release
