Repository zowe/zowe-cli, pull requests merged in 2022-08, with the labels that each got.

#1487 Created templates for bug reports and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement, area: cli

#1498 [Backport] Attempt to fix code smells
  packages/core/src/auth/Login.ts
  packages/core/src/auth/Logout.ts
  packages/zostso/src/StartTso.ts
  packages/zostso/src/TsoResponseService.ts
Labels: no-changelog

#1496 Attempt to fix some code smells
  packages/core/src/apiml/Services.ts
  packages/core/src/auth/Login.ts
  packages/core/src/auth/Logout.ts
  packages/zostso/src/StartTso.ts
  packages/zostso/src/TsoResponseService.ts
Labels: no-changelog

#1500 Update Imperative version for Zowe V1 LTS
  npm-shrinkwrap.json
  package.json
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/provisioning/package.json
  packages/workflows/package.json
  packages/zosconsole/package.json
  packages/zosfiles/package.json
  packages/zosjobs/package.json
  packages/zoslogs/package.json
  packages/zosmf/package.json
  packages/zostso/package.json
  packages/zosuss/package.json
Labels: release-patch

#1501 Update Imperative version for Zowe V2 LTS
  __tests__/__packages__/cli-test-utils/package.json
  npm-shrinkwrap.json
  package.json
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__unit__/compare/lf-uss/LocalfileUss.handler.unit.test.ts
  packages/cli/package.json
  packages/cli/src/zosfiles/compare/lf-ds/LocalfileDataset.handler.ts
  packages/cli/src/zosfiles/compare/lf-sdd/LocalfileSpooldd.handler.ts
  packages/cli/src/zosfiles/compare/lf-uss/LocalfileUss.handler.ts
  packages/core/package.json
  packages/provisioning/package.json
  packages/workflows/package.json
  packages/zosconsole/package.json
  packages/zosfiles/package.json
  packages/zosjobs/package.json
  packages/zoslogs/package.json
  packages/zosmf/package.json
  packages/zostso/package.json
  packages/zosuss/package.json
Labels: release-minor
