Repository zowe/zowe-cli, pull requests merged in 2023-11, with the labels that each got.

#1840 Restore Jest sonar reporter and bump workflow timeout
  .github/workflows/zowe-cli.yml
  jest.config.js
  npm-shrinkwrap.json
  package.json
Labels: no-changelog

#1841 Migrate pr1840
  .github/workflows/zowe-cli.yml
  jest.config.js
  npm-shrinkwrap.json
  package.json
Labels: no-changelog

#1842 Fix System Tests to Handle Running Against APIML
  .github/workflows/zowe-cli.yml
  .gitignore
  __tests__/__integration__/__snapshots__/imperative.secure.integration.test.ts.snap
  __tests__/__integration__/imperative.integration.subtest.ts
  __tests__/__integration__/imperative.secure.integration.test.ts
  __tests__/__resources__/env/integration-imperative.env
  __tests__/__resources__/env/integration-main.env
  jest.config.js
  npm-shrinkwrap.json
  package.json
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__system__/compare/ds/Compare.ds.system.test.ts
  packages/cli/__tests__/zosfiles/__system__/view/ds/View.ds.system.test.ts
  packages/cli/__tests__/zosfiles/__system__/view/uss/View.uss.system.test.ts
  packages/cli/__tests__/zoslogs/__integration__/list/__snapshots__/cli.zos-logs.list.logs.integration.test.ts.snap
  packages/cli/__tests__/zoslogs/__system__/list/cli.zos-logs.list.logs.system.test.ts
  packages/cli/__tests__/zoslogs/__unit__/__snapshots__/ZosLogs.definition.unit.test.ts.snap
  packages/cli/src/zoslogs/ZosLogs.definition.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.login.fruit.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/auth/imperative.test.cli.auth.logout.fruit.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/auto-init/imperative.test.cli.config.auto-init.fruit.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/convert-profiles/cli.imperative-test-cli.config.convert-profiles.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/init/cli.imperative-test-cli.config.init.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/profiles/__snapshots__/cli.imperative-test-cli.config.profiles.integration.test.ts.snap
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/profiles/cli.imperative-test-cli.config.profiles.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/report-env/cli.imperative-test-cli.config.report-env.integration.test.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/secure/cli.imperative-test-cli.config.secure.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/config/set/cli.imperative-test-cli.config.set.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/profiles/cli.imperative-test-cli.profiles.create.secured-profile.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/test/cli.imperative-test-cli.test.config-auto-store.integration.subtest.ts
  packages/imperative/__tests__/__integration__/imperative/__tests__/__integration__/cli/test/cli.imperative-test-cli.test.config-override.integration.subtest.ts
  packages/imperative/__tests__/__snapshots__/imperative.secure.integration.test.ts.snap
  packages/imperative/__tests__/src/example_clis/with_profiles/WithProfiles.integration.test.ts
  packages/imperative/__tests__/src/example_clis/with_profiles/__integration__/AutoGeneratedProfileCommands.integration.subtest.ts
  packages/imperative/__tests__/src/example_clis/with_profiles/__integration__/ExampleDefinitions.integration.subtest.ts
  packages/imperative/__tests__/src/example_clis/with_profiles/__integration__/ExampleLogging.integration.subtest.ts
  packages/imperative/__tests__/src/example_clis/with_profiles/__integration__/ExampleProfiles.integration.subtest.ts
  packages/imperative/__tests__/src/packages/cmd/__integration__/HelpCommands.integration.subtest.ts
  packages/imperative/__tests__/src/packages/imperative/__integration__/ConfigLoading.integration.test.ts
  packages/imperative/__tests__/src/packages/imperative/__integration__/PluginManagementFacility.integration.subtest.ts
  packages/imperative/__tests__/src/packages/imperative/plugins/suites/InstallingPlugins.ts
  packages/imperative/__tests__/src/packages/profiles/__integration__/CliProfileManager.credentials.integration.subtest.ts
  packages/zosjobs/__tests__/__system__/CancelJobs.system.test.ts
  packages/zosjobs/__tests__/__system__/DownloadJobs.system.test.ts
  packages/zosjobs/__tests__/__system__/GetJobs.system.test.ts
  sonar-project.properties
Labels: needs-ported

#1855 Fix broken package.jsons from publish error - v1
  package.json
  packages/zosjobs/package.json
  packages/zosmf/package.json
  packages/zostso/package.json
Labels: no-changelog

#1857 [Merge First!] Revert "Bump version to 7.18.11 [ci skip]"
  __tests__/__packages__/cli-test-utils/CHANGELOG.md
  __tests__/__packages__/cli-test-utils/package.json
  lerna.json
  npm-shrinkwrap.json
  packages/cli/package.json
  packages/core/package.json
  packages/imperative/package.json
  packages/provisioning/package.json
  packages/workflows/package.json
  packages/zosconsole/package.json
  packages/zosfiles/package.json
  packages/zosjobs/package.json
  packages/zoslogs/package.json
  packages/zosmf/package.json
  packages/zostso/package.json
  packages/zosuss/package.json
Labels: priority-high

#1960 Update README.md
  README.md
Labels: documentation

#1963 Update flagged code since prefix should never be null
  packages/cli/src/zosjobs/delete/old-jobs/OldJobs.handler.ts
Labels: no-changelog

#1967 Make v2 change in next
  packages/cli/src/zosjobs/delete/old-jobs/OldJobs.handler.ts
Labels: no-changelog
