Repository zowe/zowe-cli, pull requests merged in 2023-02, with the labels that each got.

#1616 Doc on merging config files
  docs/How_config_files_are_merged.md
  docs/Using Team Configuration.md
Labels: no-release

#1627 Add "link:imperative" npm script
  docs/DevelopmentTips.md
  npm-shrinkwrap.json
  package.json
Labels: no-changelog

#1635 Update stale bot to exclude `bug` and `Epic` labels
  .github/workflows/stale.yml
Labels: no-release, no-changelog

#1512 Compare command base helper
  packages/cli/__tests__/zosfiles/__unit__/compare/CompareBaseHelper.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/compare/ds/Dataset.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/compare/lf-ds/LocalfileDataset.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/compare/lf-uss/LocalfileUss.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/compare/uss/UssFile.handler.unit.test.ts
  packages/cli/src/zosfiles/compare/CompareBase.handler.ts
  packages/cli/src/zosfiles/compare/CompareBaseHelper.ts
  packages/cli/src/zosfiles/compare/doc/ICompareFileOptions.ts
  packages/cli/src/zosfiles/compare/ds/Dataset.handler.ts
  packages/cli/src/zosfiles/compare/lf-ds/LocalfileDataset.handler.ts
  packages/cli/src/zosfiles/compare/lf-sdd/LocalfileSpooldd.handler.ts
  packages/cli/src/zosfiles/compare/lf-uss/LocalfileUss.handler.ts
  packages/cli/src/zosfiles/compare/sdd/Spooldd.handler.ts
  packages/cli/src/zosfiles/compare/uss/UssFile.handler.ts
  packages/core/__tests__/utils/__unit__/ProfileUtils.unit.test.ts
  packages/zosjobs/src/CancelJobs.ts
Labels: no-changelog
