Repository zowe/zowe-cli, pull requests merged in 2024-01, with the labels that each got.

#2011 Update release config to stop publishing v2 as next
  release.config.js
Labels: no-changelog

#2006 doc(cert): Document limitation on cert files
  packages/cli/__tests__/auth/__integration__/__snapshots__/cli.auth.apiml.integration.test.ts.snap
  packages/cli/__tests__/zosuss/__integration__/issue/__snapshots__/cli.zos-uss.issue.ssh.integration.test.ts.snap
  packages/core/CHANGELOG.md
  packages/core/src/constants/Core.constants.ts
Labels: release-patch, dev-doc

#1997 Add workflow to update issue and PR status on GH project board
  .github/workflows/update-project.yml
Labels: no-changelog

#2018 Add update-project.yml workflow to next branch
  .github/workflows/update-project.yml
Labels: no-changelog

#1981 Remove deprecated for core cli
  __tests__/__packages__/cli-test-utils/src/TestUtils.ts
  npm-shrinkwrap.json
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__integration__/edit/uss/__snapshots__/edit.uss.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/edit/uss/edit.uss.integration.test.ts
  packages/cli/__tests__/zosfiles/__unit__/ZosFilesBase.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/create/binaryPds/__snapshots__/BinaryPDS.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/cPds/__snapshots__/CPDS.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/classicPds/__snapshots__/ClassicPDS.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/ds/__snapshots__/ds.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/pds/__snapshots__/Pds.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/ps/__snapshots__/Ps.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/create/vsam/__snapshots__/Vsam.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/download/dsm/DataSetMatching.handler.unit.test.ts
  packages/cli/__tests__/zosuss/__system__/issue/cli.issue.ssh.system.test.ts
  packages/cli/src/Constants.ts
  packages/cli/src/zosfiles/ZosFilesBase.handler.ts
  packages/cli/src/zosfiles/create/Create.options.ts
  packages/cli/src/zosfiles/create/Create.utils.ts
  packages/cli/src/zosfiles/create/binaryPds/BinaryPDS.definition.ts
  packages/cli/src/zosfiles/create/cPds/CPDS.definition.ts
  packages/cli/src/zosfiles/create/classicPds/ClassicPDS.definition.ts
  packages/cli/src/zosfiles/create/ds/ds.definition.ts
  packages/cli/src/zosfiles/create/pds/Pds.definition.ts
  packages/cli/src/zosfiles/create/ps/Ps.definition.ts
  packages/cli/src/zosfiles/create/vsam/vsam.definition.ts
  packages/cli/src/zosfiles/create/vsam/vsam.handler.ts
  packages/cli/src/zostso/constants/ZosTso.constants.ts
  packages/imperative/package.json
  packages/imperative/src/utilities/__tests__/CliUtils.unit.test.ts
  packages/zosfiles/CHANGELOG.md
  packages/zosfiles/__tests__/__system__/methods/create/Create.system.test.ts
  packages/zosfiles/__tests__/__unit__/methods/create/Create.unit.test.ts
  packages/zosfiles/__tests__/__unit__/utils/__snapshots__/ZosFilesUtils.unit.test.ts.snap
  packages/zosfiles/src/constants/ZosFiles.messages.ts
  packages/zosfiles/src/methods/create/Create.ts
  packages/zosfiles/src/methods/download/doc/IDownloadOptions.ts
  packages/zosjobs/CHANGELOG.md
  packages/zosjobs/__tests__/__system__/DownloadJobs.system.test.ts
  packages/zosjobs/src/DownloadJobs.ts
  packages/zosmf/CHANGELOG.md
  packages/zosmf/src/ZosmfSession.ts
  packages/zostso/CHANGELOG.md
  packages/zosuss/CHANGELOG.md
  packages/zosuss/src/Shell.ts
  packages/zosuss/src/SshSession.ts
Labels: release-current

#2029 applying accepted v3 filesEditOptions enhancements to v2
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__integration__/edit/ds/__snapshots__/edit.ds.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/edit/uss/__snapshots__/edit.uss.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/edit/Edit.utils.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/edit/ds/__snapshots__/Dataset.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/edit/uss/__snapshots__/UssFile.definition.unit.test.ts.snap
  packages/cli/src/zosfiles/-strings-/en.ts
  packages/cli/src/zosfiles/edit/Edit.handler.ts
  packages/cli/src/zosfiles/edit/Edit.options.ts
  packages/cli/src/zosfiles/edit/Edit.utils.ts
  packages/cli/src/zosfiles/edit/ds/Dataset.definition.ts
  packages/cli/src/zosfiles/edit/uss/USSFile.definition.ts
Labels: release-minor
