Repository zowe/zowe-cli, pull requests merged in 2024-12, with the labels that each got.

#2388 system test fix
  packages/zosfiles/__tests__/__system__/methods/upload/Upload.system.test.ts
  packages/zosfiles/__tests__/__unit__/methods/upload/Upload.unit.test.ts
  packages/zosfiles/src/methods/upload/Upload.ts
Labels: no-changelog

#2385 first edits to ReadMe
  README.md
Labels: documentation, cli, no-changelog

#2372 Auth order spike
  docs/Design_for_selecting_auth_type.md
  prototypes/Readme.md
  prototypes/packages/.gitkeep
  prototypes/packages/cli/src/zosfiles/list/ds/DataSet.handler.ts
  prototypes/packages/cli/src/zosfiles/list/ds/Readme.md
  prototypes/packages/imperative/src/rest/src/session/AuthOrder.ts
  prototypes/packages/imperative/src/rest/src/session/ConnectionPropsForSessCfg.ts
  prototypes/packages/imperative/src/rest/src/session/Readme.md
Labels: no-release, no-changelog
