Repository zowe/zowe-cli, pull requests merged in 2024-11, with the labels that each got.

#2314 Fix jest-stare output in wrong folder for system tests
  __tests__/__packages__/cli-test-utils/CHANGELOG.md
  __tests__/__packages__/cli-test-utils/src/TestUtils.ts
  jest.config.js
  package.json
  packages/zosjobs/__tests__/__system__/GetJobs.system.test.ts
Labels: no-changelog

#2254 Add --ignore-not-found flag logic to zosfilesBase.handler and update command definitions and en.ts for delete operations
  .gitignore
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__integration__/delete/ds/__snapshots__/cli.files.delete.ds.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/delete/uss/__snapshots__/cli.files.delete.uss.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/delete/vsam/__snapshots__/cli.files.delete.vsam.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/delete/zfs/__snapshots__/cli.files.delete.zfs.integration.test.ts.snap
  packages/cli/__tests__/zosfiles/__integration__/upload/dtu/cli.files.upload.dtu.integration.test.ts
  packages/cli/__tests__/zosfiles/__system__/delete/ds/cli.files.delete.ds.system.test.ts
  packages/cli/__tests__/zosfiles/__system__/delete/uss/__snapshots__/cli.files.delete.file.system.test.ts.snap
  packages/cli/__tests__/zosfiles/__system__/delete/uss/cli.files.delete.file.system.test.ts
  packages/cli/__tests__/zosfiles/__system__/delete/vsam/__snapshots__/cli.files.delete.vsam.system.test.ts.snap
  packages/cli/__tests__/zosfiles/__system__/delete/vsam/cli.files.delete.vsam.system.test.ts
  packages/cli/__tests__/zosfiles/__system__/delete/zfs/__snapshots__/cli.files.delete.zfs.system.test.ts.snap
  packages/cli/__tests__/zosfiles/__system__/delete/zfs/cli.files.delete.zfs.system.test.ts
  packages/cli/__tests__/zosfiles/__unit__/create/vsam/Vsam.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/create/zfs/zfs.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/delete/ds/Ds.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/delete/uss/Uss.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/delete/vsam/Vsam.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/delete/zfs/__snapshots__/zfs.definition.unit.test.ts.snap
  packages/cli/__tests__/zosfiles/__unit__/delete/zfs/zfs.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/download/dsm/DataSetMatching.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/mount/fs/fs.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/upload/ftds/FileToDataSet.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/upload/ftds/__snapshots__/FileToDataSet.handler.unit.test.ts.snap
  packages/cli/src/zosfiles/-strings-/en.ts
  packages/cli/src/zosfiles/ZosFilesBase.handler.ts
  packages/cli/src/zosfiles/delete/ds/Ds.definition.ts
  packages/cli/src/zosfiles/delete/uss/Uss.definition.ts
  packages/cli/src/zosfiles/delete/vsam/Vsam.definition.ts
  packages/cli/src/zosfiles/delete/vsam/Vsam.handler.ts
  packages/cli/src/zosfiles/delete/zfs/zfs.definition.ts
  zowe-cli.ppf
Labels: release-minor, no-changelog

#2355 Fix one last test
  packages/core/__tests__/apiml/__system__/Services.system.test.ts
Labels: no-changelog

#2361 Enhanced #2301 to include "--help-web" commands to pass even if presence of a faulty configuration
  packages/imperative/CHANGELOG.md
  packages/imperative/__tests__/__integration__/hello_world/__tests__/HelloWorldCliBadConfig.integration.test.ts
  packages/imperative/__tests__/__integration__/hello_world/__tests__/scripts/help-web.sh
  packages/imperative/src/cmd/__tests__/CommandProcessor.unit.test.ts
  packages/imperative/src/imperative/src/Imperative.ts
Labels: release-current

#2363 Help web 2
  packages/imperative/CHANGELOG.md
  packages/imperative/src/imperative/src/Imperative.ts
Labels: release-current
