Repository zowe/zowe-cli, pull requests merged in 2024-04, with the labels that each got.

#2103 porting changes from original pr #2081
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosuss/__system__/issue/cli.issue.ssh.system.test.ts
  packages/imperative/CHANGELOG.md
  packages/imperative/src/rest/__tests__/session/ConnectionPropsForSessCfg.unit.test.ts
  packages/imperative/src/rest/src/session/ConnectionPropsForSessCfg.ts
  packages/imperative/src/rest/src/session/doc/IOptionsForAddConnProps.ts
  packages/zosuss/CHANGELOG.md
  packages/zosuss/src/SshBaseHandler.ts
Labels: release-current

#2108 Update next branch with changes from master
  packages/cli/CHANGELOG.md
  packages/cli/__tests__/zosfiles/__unit__/list/am/AllMembers.handler.unit.test.ts
  packages/cli/__tests__/zosfiles/__unit__/list/am/__snapshots__/AllMembers.handler.unit.test.ts.snap
  packages/cli/src/zosfiles/list/am/AllMembers.handler.ts
  packages/imperative/CHANGELOG.md
  packages/imperative/src/rest/src/session/ConnectionPropsForSessCfg.ts
  packages/zosfiles/CHANGELOG.md
  packages/zosfiles/__tests__/__unit__/methods/list/List.unit.test.ts
  packages/zosfiles/src/methods/list/List.ts
  packages/zosuss/CHANGELOG.md
Labels: no-changelog

#2117 Create dco.yml
  .github/dco.yml
Labels: no-changelog

#2119 Reinstate token precedence over password in AbstractRestClient
  packages/imperative/CHANGELOG.md
  packages/imperative/src/rest/__tests__/client/AbstractRestClient.unit.test.ts
  packages/imperative/src/rest/__tests__/client/RestClient.unit.test.ts
  packages/imperative/src/rest/src/client/AbstractRestClient.ts
  packages/imperative/src/rest/src/session/doc/ISession.ts
Labels: API
